#!/usr/bin/env python

import sys

if len(sys.argv) > 1:
    f = open(sys.argv[1])
else:
    f = sys.stdin

for line in f:
    if line.startswith('Full thread dump '): break

for line in f:
    sys.stdout.write(line)
    if line.startswith('Heap'): break

